# Generated by Django 4.1 on 2024-01-07 14:42

from django.db import migrations
from django.contrib.auth.models import Group, Permission, ContentType
from tournaments.models import Tournament
from tournaments.models import Participant
from locations.models import Location


def create_groups_and_permissions(apps, schema_editor):

    coaches_group, created = Group.objects.get_or_create(name='Coaches')
    participants_group, created = Group.objects.get_or_create(name='Participants')

    content_type_tournament = ContentType.objects.get_for_model(Tournament)
    content_type_participant = ContentType.objects.get_for_model(Participant)
    content_type_location = ContentType.objects.get_for_model(Location)

    create_tournament_permission, created = Permission.objects.get_or_create(
        codename='create_tournament',
        name='Can create',
        content_type=content_type_tournament,
    )

    can_participate_permission, created = Permission.objects.get_or_create(
        codename='can_participate',
        name='Can participate',
        content_type=content_type_participant,
    )

    read_participants_permission, created = Permission.objects.get_or_create(
        codename='read_participants',
        name='Read participants',
        content_type=content_type_participant,
    )

    add_location_permission, created = Permission.objects.get_or_create(
        codename='add_location',
        name='Can add location',
        content_type=content_type_location,
    )

    coaches_group.permissions.add(create_tournament_permission, read_participants_permission, add_location_permission)
    participants_group.permissions.add(can_participate_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
