# Generated by Django 4.1 on 2023-12-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_enter',
            field=models.BooleanField(default=False),
        ),
    ]
