# Generated by Django 4.1 on 2023-12-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_participant_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='organizer',
            new_name='organizer_id',
        ),
    ]
