# Generated by Django 4.1 on 2023-12-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_rename_location_tournament_location_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
